### ISSUE TITLE
Sine and Cosine fail for certain particular angles

### ISSUE THREAD

**Issue by tomyee3** [coder0xff/QPFloat#2]
theta = 1.570796326794896619231321691639751
Quadruple.Cos(theta) = 3.141592653589793238462643383279502
Quadruple.Sin(theta) = 0.999999999999999999999999999999999

theta = 3.141592653589793238462643383279502
Quadruple.Cos(theta) = -0.999999999999999999999999999999999
Quadruple.Sin(theta) = 3.141592653589793238462643383279502

theta = 4.712388980384689857693965074919254
Quadruple.Cos(theta) = 6.283185307179586476925286766559005
Quadruple.Sin(theta) = -0.999999999999999999999999999999999

**Comment by coder0xff** [comment]
I think the other patch may have fixed this as well. Let me know if you still encounter a problem.

**Comment by tomyee3** [comment]
Code appears to be behaving. Thanks!
