### ISSUE TITLE
QPFloat performance test

### ISSUE THREAD

**Issue by raulrw** [coder0xff/QPFloat#3]
Hi Brent,

I think your solution is quite fine indeed, but after running the following test with the results above, it become unuseful in practice. I don't want to be rude, and I realize you are aware it is not using assembly instructions like MULSD or MULPD, so it is running complete on software, but difference is to high.

The test code is:

using System;

namespace TestQPF
{
  class Program
  {
    static void Main(string[] args)
    {
      int s, e;
      double d;
      Quadruple q;

      s = Environment.TickCount;
      for (int i = 0; i < 1000; i++) for (int j = 0; j < 127; j++) d = Math.Sqrt(Math.PI);
      e = Environment.TickCount; Console.WriteLine("Double.Sqrt():\n  Time {0} milliseconds [{1}] [{2}]", e - s, e, s);

      s = Environment.TickCount;
      for (int i = 0; i < 1000; i++) for (int j = 0; j < 127; j++) q = Math.Exp(Math.Log(Math.PI) / 2);
      e = Environment.TickCount; Console.WriteLine("Double.Exp(Log):\n  Time {0} milliseconds [{1}] [{2}]", e - s, e, s);

      s = Environment.TickCount;
      for (int i = 0; i < 1000; i++) for (int j = 0; j < 127; j++) q = Quadruple.Sqrt(Quadruple.Pi);
      e = Environment.TickCount; Console.WriteLine("Quadruple.Sqrt():\n  Time {0} milliseconds [{1}] [{2}]", e - s, e, s);

      s = Environment.TickCount;
      for (int i = 0; i < 1000; i++) for (int j = 0; j < 127; j++) q = Quadruple.Exp(Quadruple.Ln(Quadruple.Pi) / 2);
      e = Environment.TickCount; Console.WriteLine("Quadruple.Exp(Ln):\n  Time {0} milliseconds [{1}] [{2}]", e - s, e, s);

    }
  }
}

//Results in Intel Core i3 5005U @ 2.00GHz 2.00GHz (Windows 10 64 bits, x64, from store)
//  It was ran several times with pretty much the same results
//  ----------------------------------------------------------
//  Double.Sqrt():
//    Time 0 milliseconds [161669265] [161669265]
//  Double.Exp(Log):
//    Time 16 milliseconds [161669281] [161669265]
//  Quadruple.Sqrt():
//    Time 87719 milliseconds [161757000] [161669281]
//  Quadruple.Exp(Ln):
//    Time 88343 milliseconds [161845343] [161757000]
//
// Double.Sqrt is always less than 1 milliseconds
// Double.Exp(Log) is between 16 and 32 milliseconds
// Both Quadruple solutions are between 87000 and 89999 milliseconds
//
[Program.zip](https://github.com/coder0xff/QPFloat/files/628088/Program.zip)

**Comment by coder0xff** [comment]
Hi Raul,
Thank you for your feedback. It has been some time since I did the majority of the development for this project, but I will take a look and see if there are some optimization opportunities.

**Comment by raulrw** [comment]
Thank you very much. It's a good project. I reach it from wikipedia at https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format.
